# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cleanPart2 <- function(kappa) {
    .Call('_HypergeoMatRcpp_cleanPart2', PACKAGE = 'HypergeoMatRcpp', kappa)
}

dualPartition <- function(kappa, to = -1L) {
    .Call('_HypergeoMatRcpp_dualPartition', PACKAGE = 'HypergeoMatRcpp', kappa, to)
}

T_ <- function(alpha, a, b, kappa) {
    .Call('_HypergeoMatRcpp_T_', PACKAGE = 'HypergeoMatRcpp', alpha, a, b, kappa)
}

hypergeom <- function(m, a, b, x, alpha = 2.0) {
    .Call('_HypergeoMatRcpp_hypergeom', PACKAGE = 'HypergeoMatRcpp', m, a, b, x, alpha)
}

test <- function(x) {
    .Call('_HypergeoMatRcpp_test', PACKAGE = 'HypergeoMatRcpp', x)
}

test2 <- function(k) {
    .Call('_HypergeoMatRcpp_test2', PACKAGE = 'HypergeoMatRcpp', k)
}

test3 <- function(mu) {
    .Call('_HypergeoMatRcpp_test3', PACKAGE = 'HypergeoMatRcpp', mu)
}

